on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.3.1
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '8.1'
          dest: '"${HOME}/racketdist"'
          local_catalogs: $GITHUB_WORKSPACE
          sudo: never
      - name: Register local packages
        run: |
          raco pkg install -i --auto --no-setup --skip-installed sketching sketching-lib sketching-doc
          raco pkg update  --auto --no-setup sketching sketching-lib sketching-doc
      - name: Setup Collections
        run: raco setup --check-pkg-deps sketching
      - name: Build Documentation
         run: |
           ls         
           xvfb-run -a raco scribble ../sketching-doc/sketching-doc/manual-sketching.scrbl
#        run: xvfb-run -a raco setup --jobs 1 sketching-doc
